cmake_minimum_required(VERSION 4.0)
project(S5)

set(CMAKE_CXX_STANDARD 20)

add_executable(S5 A.cpp
        B.cpp
        D.cpp
        C.cpp
        D-corregido.cpp
        F.cpp
        f1.cpp
        G.cpp
        Joyas_Piedras.cpp
        registrationsystem.cpp
        prueba.cpp
        HashTable.cpp
        samedifferences.cpp)
